name: build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  scan:
    name: scan
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in repo mode
        uses: bsord/trivy-action@enable-config
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'